name: base
channels:
  - conda-forge
dependencies:
  - python=3.9
  - mastodon.py=1.8.0
  - requests
  - progressbar
  - pillow=9.4
  - pip
  - pip:
    - python-magic==0.4.27
    - simple-image-download==0.5