apiVersion: v1
kind: Secret
metadata:
  name: mastodon-credentials
  namespace: mastobot
type: Opaque
data:
  CLIENT_KEY: your_client_key_here
  CLIENT_SECRET: your_client_secret_here
  ACCESS_TOKEN: your_access_token_here