apiVersion: batch/v1
kind: CronJob
metadata:
  name: countdown-mastobot
  namespace: mastobot
spec:
  schedule: "0 12 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: countdown-mastobot
            image: ghcr.io/magsol/countdown_mastobot:latest
            imagePullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: mastodon-credentials
          restartPolicy: OnFailure